# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jschmitz <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/20 12:01:20 by jschmitz          #+#    #+#              #
#    Updated: 2024/05/20 13:28:05 by jschmitz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

SUBJ = 

OBJ =

CC = cc

CFLAG = -Wall -Werror -Wextra

RM = rm -f

clean:

fclean:	clean
	RM $(OBJ) 

re: fclean all

.PHONY: re clean fclean all
